caption_color = c_white;
caption = "";
caption_offset_y = 0;
alpha = global.gui_alpha * 3; alpha_value = 0;
pressed = 0;
callback = -1;
idx = -1;
color = c_white;
font = set_font("GUI_small");
spr = [spr_Items, ITEM.None, sprite_get_width(spr_Items), sprite_get_height(spr_Items)];
