draw_set_font(set_font("GUI_small"));
zui_set_size(128 * global.gui_scale, 32);
alpha_value = 0;
cursor_pos = 0;
callback = -1;
pressed = 0;
max_string_length = floor(__width / string_width("a")) - 1;
alpha = global.GUIHUDAlpha*2.25;
text = "";
active = false;
chars = [];
del_timer = -1;
alarm[0] = 1;