#macro BUY_TIME 60 * game_get_speed(gamespeed_fps)
#macro ROUND_STARTING_MONEY 100
#macro DILATATION_TIME 2.5 * game_get_speed(gamespeed_fps)
#macro MENU_COLOR make_color_rgb(0, 76, 76)
#macro DEFUSE_TIME 5 * game_get_speed(gamespeed_fps)
#macro ROUND_END_TIMER 5 * game_get_speed(gamespeed_fps)
#macro ROUND_WIN_REWARD 200
#macro PRONE_SPD .135
#macro WALK_SPD .5
#macro RUN_SPD 1.2
#macro ROUND_LOSS_REWARD 50
#macro HOSTAGE_RANGE 128
#macro HITMAP_KEY_BOMB -1000000
#macro ROUND_LOSS_STREAK_BONUS 75
#macro ROUND_WIN_STREAK_DEBUFF 25
#macro IS_NET instance_exists(oNetworkManager)
#macro AMMO_UPG 1.25
#macro RELOAD_UPG 0.75
#macro EQUIP_UPG 0.5
#macro MV_UPG 1.15
#macro PEN_UPG 1.1
#macro DMG_UPG 1.1
#macro SMOKE_TIME 5 * game_get_speed(gamespeed_fps)
#macro INTERPOLATION_SPD 0.3
#macro HOTBAR_SIZE 4
#macro PENETRATION_VALUE 2
#macro FLASH_LERP 0.0075
#macro MAX_FOG 20
#macro BOT_SELECT_RADIUS 512
#macro MOVE_SPD 750
#macro BULLET_SPEED 50
#macro SHADOW_DIST 24
#macro RD_OFFSET 1.0 // stabilní hráč je považován s RD_ES = 1.0
#macro RD_START 200
#macro STEALTH_DMG_MOD 3
#macro MUFFLE_VALUE 0.5
#macro STAMINA_KNIFE_HEAVY 10
#macro STAMINA_KNIFE_LIGHT 5
#macro INVENTORY_SIZE 21
#macro XP_LVL_UP_MUL 2
#macro STATS_LVL_UP 1.05
#macro INVENTORY_ROW_SIZE 7
#macro ACTIVATE_MARGIN 128
#macro DEACTIVATE_MARGIN 256
#macro DEBUG_COLOR c_aqua
#macro STAMINA_RUN_VALUE 0.5
#macro LEG_MULTIPLIER 0.7
#macro ARM_MULTIPLIER 0.9
#macro BODY_MULTIPLIER 1.1
#macro HEADSHOT_MULTIPLIER 4.1
#macro CAM view_camera[0]
#macro AMBIENT_OFFSET 1.25
#macro MAIN_COLOR make_color_rgb(255, 215, 0)
#macro FLASHLIGHT_ALPHA 0.1
#macro ALPHA_SPEED 0.01
#macro PLAYER_STARTING_VOLATILITY 0.05
#macro MIN_EP 500
#macro ES_MODIFIER 100
#macro SILVERI_EP 500
#macro SILVERII_EP 530
#macro SILVERIII_EP 580
#macro SILVERIV_EP 625
#macro SILVERV_EP 675
#macro SILVER_MASTER_EP 725
#macro GOLDI_EP 800
#macro GOLDII_EP 850
#macro GOLDIII_EP 900
#macro GOLDIV_EP 950
#macro GOLD_MASTER_EP 1025
#macro DIAMONDI_EP 1075
#macro DIAMONDII_EP 1150
#macro DIAMONDIII_EP 1225
#macro DIAMOND_MASTER_EP 1300
#macro ASSAULT_ELITEI_EP 1400
#macro ASSAULT_ELITEII_EP 1500
#macro ASSAULT_MASTER_EP 1650
#macro VERSATILE_MASTER_EP 1800
#macro EXPERIENCED_VERSATILE_MASTER_EP 2000
#macro SUPREME_MASTER_EP 2200
#macro GLOBAL_MASTER_EP 2500
#macro MAX_ROUNDS 8
#macro TRACKING_PERIOD 5
#macro ITEM_CELL_HEIGHT 24
#macro LIGHT_UPDATE 10
