/// @description console_preset(console)
function console_preset(argument0) {
	var r = (global.crosshair_color >> 16) & 0xFF;
	var g = (global.crosshair_color >> 8) & 0xFF;
	var b = global.crosshair_color & 0xFF;
	var c = argument0;
	var fullscreen = window_get_fullscreen();
	var sudo_text = " (sudo)";

	console_add(c, "sudo su (singleplayer/host)");
	console_add(c, "sudo <player id> (host)");
	console_add(c, "get id");
	console_add(c, "game restart" + sudo_text);
	console_add(c, "game exit");
	console_add(c, "reset game (main menu)" + sudo_text);
	console_add(c, "room restart" + sudo_text);
	console_add(c, "godmode {0,1} " + string(global.GodMode) + sudo_text);
	console_add(c, "give item <item id>" + sudo_text);
	console_add(c, "change team {0,1} (restart) " + string(global.player_stats.Player_team) + sudo_text);
	console_add(c, "set money <amount> [player id]" + sudo_text);
	console_add(c, "set dynamic crosshair {0,1} " + string(global.DynamicCrosshair));
	console_add(c, "set crosshair alpha <0;1> " + string(global.CrosshairAlpha));
	console_add(c, "draw bullet impact {0,1} " + string(global.DrawBulletImpact) + sudo_text);
	console_add(c, "draw admin hud {0,1} " + string(global.draw_advanced_hud) + sudo_text);
	console_add(c, "set hitbox alpha <0;1> " + string(global.HitBoxAlpha) + sudo_text);
	console_add(c, "set fullscreen {0,1} " + string(fullscreen));
	console_add(c, "set enemy movement {0,1} " + string(global.EnemyCanMove) + sudo_text);
	console_add(c, "set console height " + string(global.ConsoleHeight));
	console_add(c, "set console width " + string(global.ConsoleWidth));
	console_add(c, "set gui scale <1;2> " + string(global.gui_scale));
	console_add(c, "set fov angle <0;360> " + string(global.FieldOfView) + sudo_text);
	console_add(c, "toggle bloom {0,1} " + string(global.bloom_shader));
	console_add(c, "set time speed " + string(global.TimeSpeed) + sudo_text);
	console_add(c, "set time <minutes>" + sudo_text);
	console_add(c, "set buy time <seconds>" + sudo_text);
	console_add(c, "toggle camera shake {0,1} " + string(global.ViewShake) + sudo_text);
	console_add(c, "set player inaccuracy " + string(global.PlayerInaccuracy) + sudo_text);
	console_add(c, "clear particles {0,1}");
	console_add(c, "draw particles {0,1} " + string(global.DrawParticles));
	console_add(c, "set weather {0,1,2}" + sudo_text);
	console_add(c, "set crosshair color " + string(r) + string(g) + string(b));
	console_add(c, "draw other models {0,1} " + string(global.draw_other_models) + sudo_text);
	console_add(c, "draw damage {0,1} " + string(global.draw_damage) + sudo_text);
	console_add(c, "set window size " + string(global.window_width) + " " + string(global.window_height));
	console_add(c, "set player rating (ES) " + string(global.game_struct.Player_ep) + sudo_text);
	console_add(c, "set enemy visibility {0,1} " + string(global.enemy_visibility) + sudo_text);
	console_add(c, "set enemy rating " + string(convert_back(global.game_struct.Enemy_ep[global.game_struct.Current_game])) + sudo_text);
	console_add(c, "set played games " + string(global.game_struct.Played_games) + sudo_text);
	console_add(c, "set saturation " + string(global.saturation_level));
	console_add(c, "set aberration " + string(global.aberration_level));
	console_add(c, "set clear timer " + string(global.clear_particles_timer));
	console_add(c, "get latency");
	console_add(c, "unlock all items {0,1}" + sudo_text);
	console_add(c, "set crosshair scale " + string(global.crosshair_scale));
	console_add(c, "draw hud {0,1} " + string(global.draw_hud));
	c[? "preset"] = true;
}
