item_id = Item.None;
alpha_value = 0;
description = "";
alpha = global.GUIHUDAlpha * 3; alpha_value = 0;
icon_sprite_index = -1;
icon_image_index = -1;
outline_color = c_black;
font = set_font("GUI_small");
color = c_white;
caption = "";
drawable = true;
max_width = 150 * global.GUIMultiplier;
icon_after = false;
sprite_scale = 1;