item_id = ITEM.None;
alpha_value = 0;
description = "";
alpha = global.gui_alpha * 3; alpha_value = 0;
icon_sprite_index = -1;
icon_image_index = -1;
outline_color = c_black;
font = set_font("GUI_small");
color = c_white;
caption = "";
drawable = true;
max_width = 150 * global.gui_scale;
icon_after = false;
icon_offset = [0, 0];
sprite_scale = 1;
